vim.keymap.set("n", "s", "<Plug>Ysurround")
vim.keymap.set("n", "S", "<Plug>YSurround")
vim.keymap.set("n", "ss", "<Plug>Yssurround")
vim.keymap.set("n", "Ss", "<Plug>YSsurround")
vim.keymap.set("n", "SS", "<Plug>YSsurround")
vim.keymap.set("x", "s", "<Plug>VSurround")
vim.keymap.set("x", "gs", "<Plug>VgSurround")
