- name: Change login shell to /bin/bash
  when: ansible_facts.system == 'Darwin'
  ansible.builtin.command:
    cmd: "chsh -s /opt/homebrew/bin/bash {{ ansible_facts.user_id }}"
  become: true
  changed_when: false

- name: Find existing .bash_profile and .bashrc files
  ansible.builtin.find:
    paths: "{{ ansible_facts.user_dir }}"
    patterns:
      - ".bash_profile"
      - ".bashrc"
    file_type: file
    hidden: true
  register: bash_files

- name: Remove conflicting bash dotfiles
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ bash_files.files }}"

- name: Stow bash configuration
  ansible.builtin.command:
    cmd: >
      {{ ansible_facts.user_dir }}/.local/bin/stow --dotfiles --no-folding {{ stow_extra_args }}
      --dir={{ role_path }}/files
      --target={{ ansible_facts.user_dir }}
      config
  changed_when: false

- name: Stow extra bash configuration
  ansible.builtin.command:
    cmd: >
      {{ ansible_facts.user_dir }}/.local/bin/stow --dotfiles --no-folding {{ stow_extra_args }}
      --dir={{ bash_extra_config }}
      --target={{ ansible_facts.user_dir }}
      config
  changed_when: false
  when: bash_extra_config | length > 0
