- name: Change login shell to /bin/bash
  when: ansible_facts.system == 'Darwin'
  ansible.builtin.command:
    cmd: "chsh -s /opt/homebrew/bin/bash {{ ansible_facts.user_id }}"
  become: true
  changed_when: false

- name: Stow bash configuration
  ansible.builtin.command:
    cmd: >
      {{ ansible_facts.user_dir }}/.local/bin/stow --dotfiles --no-folding {{ stow_args }}
      --dir={{ role_path }}/files
      --target={{ ansible_facts.user_dir }}
      config
  changed_when: false

- name: Stow extra bash configuration
  ansible.builtin.command:
    cmd: >
      {{ ansible_facts.user_dir }}/.local/bin/stow --dotfiles --no-folding {{ stow_args }}
      --dir={{ bash_extra_config }}
      --target={{ ansible_facts.user_dir }}
      config
  changed_when: false
  when: bash_extra_config | length > 0
