source-file -q ~/.tmux.d/preinit.conf

# Make it use C-a, similar to screen
unbind C-b
unbind l
set -g prefix C-a

# Ensure that we can send Ctrl-A to other apps
bind C-a send-prefix

# Vim style copy / paste
set -g mode-keys vi
unbind -T copy-mode-vi v
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Use 12 hour format for time
set -g status-right " %m/%d/%Y %I:%M %p"

# History
set -g history-limit 100000

# Renumber windows
set -g renumber-windows on

# Move windows
bind-key -r < swap-window -t -1 -d
bind-key -r > swap-window -t +1 -d

# Open 10 windows on new session
set-hook -g session-created 'run-shell "for i in \$(seq \$(tmux list-windows -t #{session_name} | wc -l) 9); do tmux new-window -t #{session_name}; done; tmux select-window -t #{session_name}:0"'

# Send the same command to all panes/windows in current session
bind e command-prompt -p "Command (current session):" "run-shell '~/.scripts/tmux-send-all %1'"
bind C-e command-prompt -p "Command (current session):" "run-shell '~/.scripts/tmux-send-all %1'"

# Send the same command to all panes/windows in all sessions
bind E command-prompt -p "Command (all sessions):" "run-shell '~/.scripts/tmux-send-all --all-sessions %1'"

# Enable tmux to copy to system clipboard
set -g set-clipboard on

# Undercurl
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# From :checkhealth
set-option -sg escape-time 10
set-option -g focus-events on

source-file -q ~/.tmux.d/postinit.conf
