# Make it use C-a, similar to screen
unbind C-b
unbind l
set -g prefix C-a

# Ensure that we can send Ctrl-A to other apps
bind C-a send-prefix

# Vim style copy / paste
set -g mode-keys vi
unbind -T copy-mode-vi v
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# History
set -g history-limit 100000

# Renumber windows
set -g renumber-windows on

# Move windows
bind-key -r < swap-window -t -1 -d
bind-key -r > swap-window -t +1 -d

# Open 10 windows
set -as command-alias ten='run-shell "for i in \$(seq \$(tmux list-windows | wc -l) 9); do tmux new-window; done; tmux select-window -t 0"'

# Move window to position N
set -as command-alias window-move='run-shell "~/.scripts/tmux-move-window %1"'

# OSC 52 tmux workaround
set-option -g set-clipboard on
set -as terminal-overrides ",*:Ms=\\E]52;c;%p2%s\\7"

# Send the same command to all panes/windows in current session
bind C-e command-prompt -p "Command:" "run-shell '~/.scripts/tmux-send-all %1'"

# Undercurl
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# From :checkhealth
set-option -sg escape-time 10
set-option -g focus-events on
