- name: Check if rustup is installed
  command: "rustup --version"
  register: rustup_check
  changed_when: false
  failed_when: false

- name: Install rustup
  ansible.builtin.shell:
    cmd: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path"
  when: rustup_check.rc != 0

- name: Update Rust toolchain
  command: rustup update stable
  register: rustup_update
  changed_when: "'unchanged' not in rustup_update.stdout"

- name: Install or update cargo packages
  community.general.cargo:
    name:
    - bat
    - du-dust
    - eza
    - fd-find
    - ripgrep
    - sd
    - tealdeer
    - tokei
    - zoxide
    state: latest
