- name: Get latest fzf information
  include_tasks: "../../tasks/github_release_asset.yml"
  vars:
    github_repo: "junegunn/fzf"

- name: Install fzf from tarball
  include_tasks: "../../tasks/install_tarball.yml"
  vars:
    tarball_app_name: fzf
    tarball_url: "{{ _gh_download_url }}"
    tarball_install_dir: "{{ fzf_install_dir }}"
    tarball_binary_subpath: "fzf"
    tarball_symlink_name: "fzf"
