- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '755'
  loop:
    - "~/.tarballs"
    - "~/.bin"
    - "~/.scripts"
    - "~/.local/share/applications"
    - "~/.passfiles"
