- name: Get neovim {{ neovim_release_tag_name }} information
  include_tasks: "../../tasks/github_release_asset.yml"
  vars:
    github_repo: "neovim/neovim"
    github_release_id: "{{ neovim_release_id }}"

- name: Install neovim {{ neovim_release_tag_name }} from tarball
  include_tasks: "../../tasks/install_tarball.yml"
  vars:
    tarball_app_name: neovim
    tarball_url: "{{ _gh_download_url }}"
    tarball_install_dir: "{{ neovim_install_dir }}"
    tarball_extra_opts:
      - "--strip-components=1"
    tarball_binary_subpath: "bin/nvim"
    tarball_symlink_name: "nvim"

- name: Ensure neovim config directory exists
  ansible.builtin.file:
    path: "~/.config/nvim"
    state: directory
    mode: '755'

- name: Stow neovim configuration
  ansible.builtin.command:
    cmd: >
      {{ ansible_facts.user_dir }}/.local/bin/stow --dotfiles --no-folding {{ stow_extra_args }}
      --dir={{ role_path }}/files
      --target={{ ansible_facts.user_dir }}/.config/nvim
      config
  changed_when: false

- name: Install tree-sitter CLI via cargo binstall
  ansible.builtin.command:
    cmd: "{{ ansible_facts.user_dir }}/.cargo/bin/cargo binstall --no-confirm tree-sitter-cli"
  register: treesitter_binstall
  changed_when: "'is already installed' not in treesitter_binstall.stdout"

- name: Stow osc52 neovim configuration
  ansible.builtin.command:
    cmd: >
      {{ ansible_facts.user_dir }}/.local/bin/stow --dotfiles --no-folding {{ stow_extra_args }}
      --dir={{ role_path }}/files
      --target={{ ansible_facts.user_dir }}/.config/nvim
      osc52
  changed_when: false
  when: neovim_osc52_enabled

- name: Stow extra neovim configuration
  ansible.builtin.command:
    cmd: >
      {{ ansible_facts.user_dir }}/.local/bin/stow --dotfiles --no-folding {{ stow_extra_args }}
      --dir={{ neovim_extra_config }}
      --target={{ ansible_facts.user_dir }}/.config/nvim
      config
  changed_when: false
  when: neovim_extra_config | length > 0
